services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite-data:/app/src/db_volume
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend:
    build: ./backend/frontend
    volumes:
      - ./backend/frontend/dist:/app/dist

volumes:
  sqlite-data:
    driver: local
