services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite-data:/app/src/db_volume
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  sqlite-data:
